apiVersion: kaptain.org/1.7
kind: layer-and-layerset-build
metadata:
  description: "Layer and layerset build layerset - composes quality and build settings"

spec:
  layers:
    - layer-github-flow-strict:[1.2,2.0)
    - layer-and-layerset-build:[1.4,2.0)
