apiVersion: kaptain.org/1.11
kind: layer-and-layerset-build
metadata:
  description: "Layer and layerset build layerset - composes quality and build settings"

spec:
  layers:
    - layer-github-flow-strict:[1.3,2.0)
    - layer-and-layerset-build:[1.6,2.0)
