apiVersion: kaptain.org/1.29
kind: layer-and-layerset-build
metadata:
  description: "Layer and layerset build layerset - composes quality and build settings"

spec:
  layers:
    - layer-github-flow-strict:[1.3,2.0)
    - layer-and-layerset-build:[1.6,2.0)
    - layer-gh-release-how-to-use-short-first:[1.1,2.0)
